version: '3'

networks:
  kong-net:
    name: kong-net

services:
  service_a:
    container_name: service_a
    build: .
    entrypoint: python a.py
    expose:
      - 5000
    ports:
      - 5000:5000
    networks:
      - kong-net
  service_b:
    container_name: service_b
    build: .
    entrypoint: python b.py
    expose:
      - 5001
    ports:
      - 5001:5001
    networks:
      - kong-net